// This code automatically generated by TableCodeGen
using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using System.Collections.Generic;
using System;


public class ExoplanetCSV : MonoBehaviour
{
	public TextAsset file;

	public string starName;
	private float starX;
	private float starY;
	private float starZ;
	private float starRA;
	private float starDEC;
	private float starDISTps;
	private float starDISTly;
	private float starColor; 
	private float starRadius;

	private string planetName;
	private float planetX;
	private float planetY;
	private float planetOrbMax;
	private float planetRadius;

	public float testNumber;

	//private Renderer planetRenderer;
	//private Rigidbody planetRigidBody;

	void Start ()
	{
		Load (file);
	}

	public class Row
	{
		public string rowid;
		public string pl_hostname;
		public string pl_letter;
		public string pl_discmethod;
		public string pl_pnum;
		public string pl_orbper;
		public string pl_orbperlim;
		public string pl_orbsmax;
		public string pl_orbsmaxlim;
		public string pl_orbeccen;
		public string pl_orbeccenlim;
		public string pl_orbincl;
		public string pl_orbincllim;
		public string pl_bmassj;
		public string pl_bmassjlim;
		public string pl_bmassprov;
		public string pl_radj;
		public string pl_radjlim;
		public string pl_dens;
		public string pl_denslim;
		public string pl_ttvflag;
		public string pl_kepflag;
		public string pl_k2flag;
		public string pl_nnotes;
		public string ra_str;
		public string ra;
		public string dec_str;
		public string dec;
		public string st_dist;
		public string st_distlim;
		public string st_optmag;
		public string st_optmagerr;
		public string st_optmaglim;
		public string st_optmagblend;
		public string st_optband;
		public string st_teff;
		public string st_tefflim;
		public string st_teffblend;
		public string st_mass;
		public string st_masslim;
		public string st_massblend;
		public string st_rad;
		public string st_radlim;
		public string st_radblend;
		public string TEFF_COLOR;


	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}





	public class planetSystem {

		//private float planetZ;
		//private float orbitDiameter;

		public planetSystem(
			string starName, 
			float starX, 
			float starY, 
			float starZ, 
			float starColor, 
			float starRadius, 
			string planetName, 
			float planetOrbMax,
			float planetRadius )
		{


			//create new star primitive
			GameObject star = GameObject.CreatePrimitive (PrimitiveType.Sphere);
			star.name = starName;
			star.tag = "star";
			star.transform.position = new Vector3 (starX, starY, starZ);
			star.transform.localScale = new Vector3 (starRadius, starRadius, starRadius);

			// Add properties to StellarSystemProps script to be access when creating new scene
			star.AddComponent<StellarSystemProps>();
			var starProps = star.GetComponent<StellarSystemProps>();
			starProps.starName = starName;
			starProps.starX = starX;
			starProps.starY = starY; 
			starProps.starZ = starZ; 
			starProps.starColor = starColor; 
			starProps.starRadius = starRadius; 
			starProps.planetName = planetName;
			starProps.planetOrbMax = planetOrbMax;
			starProps.planetRadius = planetRadius;

			// Add star rigidbody component
			Rigidbody starRigidBody = star.AddComponent<Rigidbody> ();
			starRigidBody.mass = 0;
			starRigidBody.useGravity = false;
			starRigidBody.isKinematic = true;


			//Define star color attributes
//			Material blueStarMaterial = Resources.Load ("blueStarMaterial", typeof(Material)) as Material;
//			Material cyanStarMaterial = Resources.Load ("cyanStarMaterial", typeof(Material)) as Material;
//			Material yellowStarMaterial = Resources.Load ("yellowStarMaterial", typeof(Material)) as Material;
//			Material greenStarMaterial = Resources.Load ("greenStarMaterial", typeof(Material)) as Material;
//			Material orangeStarMaterial = Resources.Load ("orangeStarMaterial", typeof(Material)) as Material;
//			Material redStarMaterial = Resources.Load ("redStarMaterial", typeof(Material)) as Material;
			Material orbitalSphereMaterial = Resources.Load ("orbitalSphereMaterial", typeof(Material)) as Material;

			Material blueStarMaterial = Resources.Load ("LocalStarBody-Blue-001", typeof(Material)) as Material;
			Material yellowStarMaterial = Resources.Load ("LocalStarBody-Yellow-001", typeof(Material)) as Material;
			Material orangeStarMaterial = Resources.Load ("LocalStarBody-Orange-001", typeof(Material)) as Material;
			Material redStarMaterial = Resources.Load ("LocalStarBody-Red-001", typeof(Material)) as Material;

			if(starColor <= 3500)
			{
				star.GetComponent<Renderer>().material = redStarMaterial;
			}
			else if(starColor >= 3501 && starColor <= 5000)
			{
				star.GetComponent<Renderer>().material = orangeStarMaterial;
			}
			else if(starColor >= 5001 && starColor <= 6000)
			{
				star.GetComponent<Renderer>().material = yellowStarMaterial;
			}
			else if(starColor >= 6001 )
			{
				star.GetComponent<Renderer>().material = blueStarMaterial;
			}
//			else if(starColor >= 4001 && starColor <= 5000)
//			{
//				star.GetComponent<Renderer>().material = greenStarMaterial;
//			}
//			else if(starColor >= 5001 && starColor <= 8000)
//			{
//				star.GetComponent<Renderer>().material = cyanStarMaterial;
//			}
//			else if (starColor >= 8001)
//			{
//				star.GetComponent<Renderer>().material = blueStarMaterial;
//			}

			//Create new planet primitive
			GameObject planet = GameObject.CreatePrimitive (PrimitiveType.Sphere);
			planet.transform.parent = star.transform;
			//planet.AddComponent<Orbiter>();
			//planet.GetComponent<Orbiter>().orbitSpeed = 50;
			planet.name = planetName;
			planet.tag = "planet";
			var planetZ = starZ + planetOrbMax;
			planet.transform.position = new Vector3 (starX, starY, planetZ);
			planet.transform.localScale = new Vector3 (planetRadius, planetRadius, planetRadius); 

			//// Add star rigidbody component
			Rigidbody planetRigidBody = planet.AddComponent<Rigidbody> ();
			planetRigidBody.mass = 0;
			planetRigidBody.useGravity = false;
			planetRigidBody.isKinematic = true;

			TrailRenderer planetTrail;
			GameObject planetTrailObj = new GameObject();
			planetTrailObj.name = planetName + "_trail";
			planetTrailObj.transform.parent = planet.transform;
			planetTrailObj.transform.localPosition = Vector3.zero;
			planetTrail = planetTrailObj.AddComponent<TrailRenderer>();
			planetTrail.time = Mathf.Infinity;
			planetTrail.startWidth = 0.2F;
			planetTrail.endWidth = 0.2F;
			planetTrailObj.GetComponent<TrailRenderer>().material = orbitalSphereMaterial;

			GameObject player = GameObject.FindGameObjectWithTag("GameController");
			//float distToStar = Vector3.Distance(planet.transform.position, player.transform.position);


//			var textColorOpacity = ConvertRange(0f,10000f,1f,0f,distToStar);
//			//Create new text element and attach object label script
//			GameObject canvas = GameObject.FindGameObjectWithTag("CanvasLabels");
//			GameObject textGO = new GameObject (starName + "_labelCont");
//			textGO.transform.SetParent (canvas.transform);
//			var text = textGO.AddComponent<GUIText> ();
//			text.text = starName;
//			text.tag = "star_label";
//			text.color = new Color(1f,1f,1f,textColorOpacity);
//			var objLabel = textGO.AddComponent<ObjectLabel> ();
//			objLabel.target = star.transform;
//			objLabel.clampToScreen = false;

		}


	}


	void Update ()
	{
//		GameObject player = GameObject.FindGameObjectWithTag("GameController");
//		GameObject star = GameObject.FindGameObjectWithTag("star");
//		//GUIText starLabel = GameObject.FindWithTag("star_label").GetComponent<GUIText>() as GUIText;
//		GUIText[] starLabels = FindObjectsOfType(typeof(GUIText)) as GUIText[];
//
//		foreach (GUIText starLabel in starLabels) {
//			float distToStar = Vector3.Distance(star.transform.position, player.transform.position);
//
//
//			var textColorOpacity = ConvertRange(0f,1000f,1f,0f,distToStar);
//			starLabel.color = new Color(1f,1f,1f,textColorOpacity);
//			Debug.Log (textColorOpacity);
//			Debug.Log (starLabel.color);
//		}

	}

	// Formula to convert z-axis range from -1/1 to a new range
	// Called in FixedUpdate class
	public static float ConvertRange(
		float originalStart, float originalEnd,
		float newStart, float newEnd,
		float value)
	{

		float originalDiff = originalEnd - originalStart;
		float newDiff = (newEnd - newStart);
		float ratio = newDiff / originalDiff;
		float newProduct = value * ratio;
		float finalValue = (newProduct + newStart) + (newDiff/2);
		return finalValue; 

	}

	public float starXcalc (float starRA, float starDEC, float starDISTly)
	{
		return Mathf.Cos(starRA * (Mathf.PI / 180)) * (Mathf.Cos (starDEC * (Mathf.PI / 180)) * starDISTly);
	}

	public float starYcalc (float starRA, float starDEC, float starDISTly)
	{
		return Mathf.Sin (starDEC * (Mathf.PI / 180)) * starDISTly;
	}

	public float starZcalc (float starRA, float starDEC, float starDISTly)
	{
		return 1 * (Mathf.Sin (starRA * (Mathf.PI / 180)) * (Mathf.Cos (starDEC * (Mathf.PI / 180)) * starDISTly));
	}


	public void Load(TextAsset csv)
	{ 

		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.rowid = grid[i][0];
			row.pl_hostname = grid[i][1];
			row.pl_letter = grid[i][2];
			row.pl_discmethod = grid[i][3];
			row.pl_pnum = grid[i][4];
			row.pl_orbper = grid[i][5];
			row.pl_orbperlim = grid[i][6];
			row.pl_orbsmax = grid[i][7];
			row.pl_orbsmaxlim = grid[i][8];
			row.pl_orbeccen = grid[i][9];
			row.pl_orbeccenlim = grid[i][10];
			row.pl_orbincl = grid[i][11];
			row.pl_orbincllim = grid[i][12];
			row.pl_bmassj = grid[i][13];
			row.pl_bmassjlim = grid[i][14];
			row.pl_bmassprov = grid[i][15];
			row.pl_radj = grid[i][16];
			row.pl_radjlim = grid[i][17];
			row.pl_dens = grid[i][18];
			row.pl_denslim = grid[i][19];
			row.pl_ttvflag = grid[i][20];
			row.pl_kepflag = grid[i][21];
			row.pl_k2flag = grid[i][22];
			row.pl_nnotes = grid[i][23];
			row.ra_str = grid[i][24];
			row.ra = grid[i][25];
			row.dec_str = grid[i][26];
			row.dec = grid[i][27];
			row.st_dist = grid[i][28];
			row.st_distlim = grid[i][29];
			row.st_optmag = grid[i][30];
			row.st_optmagerr = grid[i][31];
			row.st_optmaglim = grid[i][32];
			row.st_optmagblend = grid[i][33];
			row.st_optband = grid[i][34];
			row.st_teff = grid[i][35];
			row.st_tefflim = grid[i][36];
			row.st_teffblend = grid[i][37];
			row.st_mass = grid[i][38];
			row.st_masslim = grid[i][39];
			row.st_massblend = grid[i][40];
			row.st_rad = grid[i][41];
			row.st_radlim = grid[i][42];
			row.st_radblend = grid[i][43];
			row.TEFF_COLOR = grid[i][43];

			//assign data to variable
			starName = row.pl_hostname;
			starRA = float.Parse (row.ra);
			starDEC = float.Parse (row.dec);
			starDISTps = float.Parse (row.st_dist); //<AU> 
			starColor = float.Parse (row.st_teff);
			starRadius = float.Parse (row.st_rad); //<JR> 1 Jupiter Radii == .1 Solar Radii
			planetName =  starName + "_" + row.pl_letter;
			planetOrbMax = float.Parse (row.pl_orbsmax);
			planetRadius = float.Parse (row.pl_radj); //<JR> 1 Jupiter Radii == .1 Solar Radii

			float JupRad_To_Km = 69911;
			float SolRad_To_Km = 695700;
			float AstUnit_To_Km = 149600000;

			//convert parsec to light year
			starDISTly = starDISTps * 3.26F;

			planetRadius = (planetRadius * JupRad_To_Km) * .000001f; //Normalized to Km;
			starRadius = (starRadius * SolRad_To_Km) * .000001f; //Normalized to Km;
			planetOrbMax = (planetOrbMax * AstUnit_To_Km) * .000001f; //Normalized to Km;

			//convert RA, Dec, and Distance to XYZ
			starX = 20 * (starXcalc (starRA, starDEC, starDISTly));
			starY = 20 * (starYcalc (starRA, starDEC, starDISTly));
			starZ = 20 * (starZcalc (starRA, starDEC, starDISTly));
			//starZ = 10 * starDISTly;


			//create new planet system
			if (starDISTly != 0) {
				//if (starName == "2MASS J02192210-3925225") {
//				Debug.Log ("StarName: " + starName);
//				Debug.Log ("Star Radii in km: " + starRadius);
//				Debug.Log ("Planet Radii in km: " + planetRadius);
				//}
				new planetSystem (starName, starX, starY, starZ, starColor, starRadius, planetName, planetOrbMax, planetRadius);
			}

			rowList.Add(row);
		}
		isLoaded = true;
	}


	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_rowid(string find)
	{
		return rowList.Find(x => x.rowid == find);
	}
	public List<Row> FindAll_rowid(string find)
	{
		return rowList.FindAll(x => x.rowid == find);
	}
	public Row Find_pl_hostname(string find)
	{
		return rowList.Find(x => x.pl_hostname == find);
	}
	public List<Row> FindAll_pl_hostname(string find)
	{
		return rowList.FindAll(x => x.pl_hostname == find);
	}
	public Row Find_pl_letter(string find)
	{
		return rowList.Find(x => x.pl_letter == find);
	}
	public List<Row> FindAll_pl_letter(string find)
	{
		return rowList.FindAll(x => x.pl_letter == find);
	}
	public Row Find_pl_discmethod(string find)
	{
		return rowList.Find(x => x.pl_discmethod == find);
	}
	public List<Row> FindAll_pl_discmethod(string find)
	{
		return rowList.FindAll(x => x.pl_discmethod == find);
	}
	public Row Find_pl_pnum(string find)
	{
		return rowList.Find(x => x.pl_pnum == find);
	}
	public List<Row> FindAll_pl_pnum(string find)
	{
		return rowList.FindAll(x => x.pl_pnum == find);
	}
	public Row Find_pl_orbper(string find)
	{
		return rowList.Find(x => x.pl_orbper == find);
	}
	public List<Row> FindAll_pl_orbper(string find)
	{
		return rowList.FindAll(x => x.pl_orbper == find);
	}
	public Row Find_pl_orbperlim(string find)
	{
		return rowList.Find(x => x.pl_orbperlim == find);
	}
	public List<Row> FindAll_pl_orbperlim(string find)
	{
		return rowList.FindAll(x => x.pl_orbperlim == find);
	}
	public Row Find_pl_orbsmax(string find)
	{
		return rowList.Find(x => x.pl_orbsmax == find);
	}
	public List<Row> FindAll_pl_orbsmax(string find)
	{
		return rowList.FindAll(x => x.pl_orbsmax == find);
	}
	public Row Find_pl_orbsmaxlim(string find)
	{
		return rowList.Find(x => x.pl_orbsmaxlim == find);
	}
	public List<Row> FindAll_pl_orbsmaxlim(string find)
	{
		return rowList.FindAll(x => x.pl_orbsmaxlim == find);
	}
	public Row Find_pl_orbeccen(string find)
	{
		return rowList.Find(x => x.pl_orbeccen == find);
	}
	public List<Row> FindAll_pl_orbeccen(string find)
	{
		return rowList.FindAll(x => x.pl_orbeccen == find);
	}
	public Row Find_pl_orbeccenlim(string find)
	{
		return rowList.Find(x => x.pl_orbeccenlim == find);
	}
	public List<Row> FindAll_pl_orbeccenlim(string find)
	{
		return rowList.FindAll(x => x.pl_orbeccenlim == find);
	}
	public Row Find_pl_orbincl(string find)
	{
		return rowList.Find(x => x.pl_orbincl == find);
	}
	public List<Row> FindAll_pl_orbincl(string find)
	{
		return rowList.FindAll(x => x.pl_orbincl == find);
	}
	public Row Find_pl_orbincllim(string find)
	{
		return rowList.Find(x => x.pl_orbincllim == find);
	}
	public List<Row> FindAll_pl_orbincllim(string find)
	{
		return rowList.FindAll(x => x.pl_orbincllim == find);
	}
	public Row Find_pl_bmassj(string find)
	{
		return rowList.Find(x => x.pl_bmassj == find);
	}
	public List<Row> FindAll_pl_bmassj(string find)
	{
		return rowList.FindAll(x => x.pl_bmassj == find);
	}
	public Row Find_pl_bmassjlim(string find)
	{
		return rowList.Find(x => x.pl_bmassjlim == find);
	}
	public List<Row> FindAll_pl_bmassjlim(string find)
	{
		return rowList.FindAll(x => x.pl_bmassjlim == find);
	}
	public Row Find_pl_bmassprov(string find)
	{
		return rowList.Find(x => x.pl_bmassprov == find);
	}
	public List<Row> FindAll_pl_bmassprov(string find)
	{
		return rowList.FindAll(x => x.pl_bmassprov == find);
	}
	public Row Find_pl_radj(string find)
	{
		return rowList.Find(x => x.pl_radj == find);
	}
	public List<Row> FindAll_pl_radj(string find)
	{
		return rowList.FindAll(x => x.pl_radj == find);
	}
	public Row Find_pl_radjlim(string find)
	{
		return rowList.Find(x => x.pl_radjlim == find);
	}
	public List<Row> FindAll_pl_radjlim(string find)
	{
		return rowList.FindAll(x => x.pl_radjlim == find);
	}
	public Row Find_pl_dens(string find)
	{
		return rowList.Find(x => x.pl_dens == find);
	}
	public List<Row> FindAll_pl_dens(string find)
	{
		return rowList.FindAll(x => x.pl_dens == find);
	}
	public Row Find_pl_denslim(string find)
	{
		return rowList.Find(x => x.pl_denslim == find);
	}
	public List<Row> FindAll_pl_denslim(string find)
	{
		return rowList.FindAll(x => x.pl_denslim == find);
	}
	public Row Find_pl_ttvflag(string find)
	{
		return rowList.Find(x => x.pl_ttvflag == find);
	}
	public List<Row> FindAll_pl_ttvflag(string find)
	{
		return rowList.FindAll(x => x.pl_ttvflag == find);
	}
	public Row Find_pl_kepflag(string find)
	{
		return rowList.Find(x => x.pl_kepflag == find);
	}
	public List<Row> FindAll_pl_kepflag(string find)
	{
		return rowList.FindAll(x => x.pl_kepflag == find);
	}
	public Row Find_pl_k2flag(string find)
	{
		return rowList.Find(x => x.pl_k2flag == find);
	}
	public List<Row> FindAll_pl_k2flag(string find)
	{
		return rowList.FindAll(x => x.pl_k2flag == find);
	}
	public Row Find_pl_nnotes(string find)
	{
		return rowList.Find(x => x.pl_nnotes == find);
	}
	public List<Row> FindAll_pl_nnotes(string find)
	{
		return rowList.FindAll(x => x.pl_nnotes == find);
	}
	public Row Find_ra_str(string find)
	{
		return rowList.Find(x => x.ra_str == find);
	}
	public List<Row> FindAll_ra_str(string find)
	{
		return rowList.FindAll(x => x.ra_str == find);
	}
	public Row Find_ra(string find)
	{
		return rowList.Find(x => x.ra == find);
	}
	public List<Row> FindAll_ra(string find)
	{
		return rowList.FindAll(x => x.ra == find);
	}
	public Row Find_dec_str(string find)
	{
		return rowList.Find(x => x.dec_str == find);
	}
	public List<Row> FindAll_dec_str(string find)
	{
		return rowList.FindAll(x => x.dec_str == find);
	}
	public Row Find_dec(string find)
	{
		return rowList.Find(x => x.dec == find);
	}
	public List<Row> FindAll_dec(string find)
	{
		return rowList.FindAll(x => x.dec == find);
	}
	public Row Find_st_dist(string find)
	{
		return rowList.Find(x => x.st_dist == find);
	}
	public List<Row> FindAll_st_dist(string find)
	{
		return rowList.FindAll(x => x.st_dist == find);
	}
	public Row Find_st_distlim(string find)
	{
		return rowList.Find(x => x.st_distlim == find);
	}
	public List<Row> FindAll_st_distlim(string find)
	{
		return rowList.FindAll(x => x.st_distlim == find);
	}
	public Row Find_st_optmag(string find)
	{
		return rowList.Find(x => x.st_optmag == find);
	}
	public List<Row> FindAll_st_optmag(string find)
	{
		return rowList.FindAll(x => x.st_optmag == find);
	}
	public Row Find_st_optmagerr(string find)
	{
		return rowList.Find(x => x.st_optmagerr == find);
	}
	public List<Row> FindAll_st_optmagerr(string find)
	{
		return rowList.FindAll(x => x.st_optmagerr == find);
	}
	public Row Find_st_optmaglim(string find)
	{
		return rowList.Find(x => x.st_optmaglim == find);
	}
	public List<Row> FindAll_st_optmaglim(string find)
	{
		return rowList.FindAll(x => x.st_optmaglim == find);
	}
	public Row Find_st_optmagblend(string find)
	{
		return rowList.Find(x => x.st_optmagblend == find);
	}
	public List<Row> FindAll_st_optmagblend(string find)
	{
		return rowList.FindAll(x => x.st_optmagblend == find);
	}
	public Row Find_st_optband(string find)
	{
		return rowList.Find(x => x.st_optband == find);
	}
	public List<Row> FindAll_st_optband(string find)
	{
		return rowList.FindAll(x => x.st_optband == find);
	}
	public Row Find_st_teff(string find)
	{
		return rowList.Find(x => x.st_teff == find);
	}
	public List<Row> FindAll_st_teff(string find)
	{
		return rowList.FindAll(x => x.st_teff == find);
	}
	public Row Find_st_tefflim(string find)
	{
		return rowList.Find(x => x.st_tefflim == find);
	}
	public List<Row> FindAll_st_tefflim(string find)
	{
		return rowList.FindAll(x => x.st_tefflim == find);
	}
	public Row Find_st_teffblend(string find)
	{
		return rowList.Find(x => x.st_teffblend == find);
	}
	public List<Row> FindAll_st_teffblend(string find)
	{
		return rowList.FindAll(x => x.st_teffblend == find);
	}
	public Row Find_st_mass(string find)
	{
		return rowList.Find(x => x.st_mass == find);
	}
	public List<Row> FindAll_st_mass(string find)
	{
		return rowList.FindAll(x => x.st_mass == find);
	}
	public Row Find_st_masslim(string find)
	{
		return rowList.Find(x => x.st_masslim == find);
	}
	public List<Row> FindAll_st_masslim(string find)
	{
		return rowList.FindAll(x => x.st_masslim == find);
	}
	public Row Find_st_massblend(string find)
	{
		return rowList.Find(x => x.st_massblend == find);
	}
	public List<Row> FindAll_st_massblend(string find)
	{
		return rowList.FindAll(x => x.st_massblend == find);
	}
	public Row Find_st_rad(string find)
	{
		return rowList.Find(x => x.st_rad == find);
	}
	public List<Row> FindAll_st_rad(string find)
	{
		return rowList.FindAll(x => x.st_rad == find);
	}
	public Row Find_st_radlim(string find)
	{
		return rowList.Find(x => x.st_radlim == find);
	}
	public List<Row> FindAll_st_radlim(string find)
	{
		return rowList.FindAll(x => x.st_radlim == find);
	}
	public Row Find_st_radblend(string find)
	{
		return rowList.Find(x => x.st_radblend == find);
	}
	public List<Row> FindAll_st_radblend(string find)
	{
		return rowList.FindAll(x => x.st_radblend == find);
	}
	public Row Find_TEFF_COLOR(string find)
	{
		return rowList.Find(x => x.TEFF_COLOR == find);
	}
	public List<Row> FindAll_TEFF_COLOR(string find)
	{
		return rowList.FindAll(x => x.TEFF_COLOR == find);
	}

}