// This code automatically generated by TableCodeGen
/*using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ExoplanetTable : MonoBehaviour
{
	public TextAsset file;

	public Renderer planetRenderer;
	public Rigidbody planetRigidBody;

	private float planetX;
	private float planetY;
	private float planetZ;

	void Start ()
	{
		Load (file);
		//Debug.Log(Find_mpl_hostname ("CoRoT-25").ra);
		//Debug.Log(GetRowList());



		//planetX = float.Parse(Find_mpl_hostname ("CoRoT-25").ra);
		//planetY = float.Parse(Find_mpl_hostname ("CoRoT-25").dec);
		//planetX = 5;
		//planetY = 5;
		//planetZ = 5;

		//GameObject planet = GameObject.CreatePrimitive (PrimitiveType.Sphere);
		//planet.transform.position = new Vector3 (planetX, planetY, planetZ);

		//Rigidbody planetRigidBody = planet.AddComponent<Rigidbody> ();
		//planet.AddComponent<Animation>();
		//planet.AddComponent<MeshFilter>();
		//planet.AddComponent<MeshCollider>();
		//planet.AddComponent<MeshRenderer>();

		//planetRigidBody.mass = 0;
		//planetRigidBody.useGravity = false;
	}

	public class Row
	{
		public string mpl_hostname;
		public string mpl_letter;
		public string mpl_def;
		public string mpl_reflink;
		public string mpl_discmethod;
		public string mpl_pnum;
		public string mpl_orbper;
		public string mpl_orbpererr1;
		public string mpl_orbpererr2;
		public string mpl_orbperlim;
		public string mpl_orbsmax;
		public string mpl_orbsmaxerr1;
		public string mpl_orbsmaxerr2;
		public string mpl_orbsmaxlim;
		public string mpl_orbeccen;
		public string mpl_orbeccenerr1;
		public string mpl_orbeccenerr2;
		public string mpl_orbeccenlim;
		public string mpl_orbincl;
		public string mpl_orbinclerr1;
		public string mpl_orbinclerr2;
		public string mpl_orbincllim;
		public string mpl_bmassj;
		public string mpl_bmassjerr1;
		public string mpl_bmassjerr2;
		public string mpl_bmassjlim;
		public string mpl_bmassprov;
		public string mpl_radj;
		public string mpl_radjerr1;
		public string mpl_radjerr2;
		public string mpl_radjlim;
		public string mpl_dens;
		public string mpl_denserr1;
		public string mpl_denserr2;
		public string mpl_denslim;
		public string ra;
		public string raerr;
		public string dec;
		public string decerr;
		public string mst_teff;
		public string mst_tefferr1;
		public string mst_tefferr2;
		public string mst_tefflim;
		public string mst_teffblend;
		public string mst_mass;
		public string mst_masserr1;
		public string mst_masserr2;
		public string mst_masslim;
		public string mst_massblend;
		public string mst_rad;
		public string mst_raderr1;
		public string mst_raderr2;
		public string mst_radlim;
		public string mst_radblend;
		public string rowupdate;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.mpl_hostname = grid[i][0];
			row.mpl_letter = grid[i][1];
			row.mpl_def = grid[i][2];
			row.mpl_reflink = grid[i][3];
			row.mpl_discmethod = grid[i][4];
			row.mpl_pnum = grid[i][5];
			row.mpl_orbper = grid[i][6];
			row.mpl_orbpererr1 = grid[i][7];
			row.mpl_orbpererr2 = grid[i][8];
			row.mpl_orbperlim = grid[i][9];
			row.mpl_orbsmax = grid[i][10];
			row.mpl_orbsmaxerr1 = grid[i][11];
			row.mpl_orbsmaxerr2 = grid[i][12];
			row.mpl_orbsmaxlim = grid[i][13];
			row.mpl_orbeccen = grid[i][14];
			row.mpl_orbeccenerr1 = grid[i][15];
			row.mpl_orbeccenerr2 = grid[i][16];
			row.mpl_orbeccenlim = grid[i][17];
			row.mpl_orbincl = grid[i][18];
			row.mpl_orbinclerr1 = grid[i][19];
			row.mpl_orbinclerr2 = grid[i][20];
			row.mpl_orbincllim = grid[i][21];
			row.mpl_bmassj = grid[i][22];
			row.mpl_bmassjerr1 = grid[i][23];
			row.mpl_bmassjerr2 = grid[i][24];
			row.mpl_bmassjlim = grid[i][25];
			row.mpl_bmassprov = grid[i][26];
			row.mpl_radj = grid[i][27];
			row.mpl_radjerr1 = grid[i][28];
			row.mpl_radjerr2 = grid[i][29];
			row.mpl_radjlim = grid[i][30];
			row.mpl_dens = grid[i][31];
			row.mpl_denserr1 = grid[i][32];
			row.mpl_denserr2 = grid[i][33];
			row.mpl_denslim = grid[i][34];
			row.ra = grid[i][35];
			row.raerr = grid[i][36];
			row.dec = grid[i][37];
			row.decerr = grid[i][38];
			row.mst_teff = grid[i][39];
			row.mst_tefferr1 = grid[i][40];
			row.mst_tefferr2 = grid[i][41];
			row.mst_tefflim = grid[i][42];
			row.mst_teffblend = grid[i][43];
			row.mst_mass = grid[i][44];
			row.mst_masserr1 = grid[i][45];
			row.mst_masserr2 = grid[i][46];
			row.mst_masslim = grid[i][47];
			row.mst_massblend = grid[i][48];
			row.mst_rad = grid[i][49];
			row.mst_raderr1 = grid[i][50];
			row.mst_raderr2 = grid[i][51];
			row.mst_radlim = grid[i][52];
			row.mst_radblend = grid[i][53];
			row.rowupdate = grid[i][54];

			planetX = float.Parse(row.ra);
			planetY = float.Parse(row.dec);
			planetZ = float.Parse (row.mpl_bmassj);

			GameObject planet = GameObject.CreatePrimitive (PrimitiveType.Sphere);
			planet.transform.position = new Vector3 (planetX, planetY, planetZ);

			Rigidbody planetRigidBody = planet.AddComponent<Rigidbody> ();

			planetRigidBody.mass = 0;
			planetRigidBody.useGravity = false;


			Debug.Log(planetX);
			Debug.Log(planetY);
			Debug.Log(planetZ);


			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_mpl_hostname(string find)
	{
		return rowList.Find(x => x.mpl_hostname == find);
	}
	public List<Row> FindAll_mpl_hostname(string find)
	{
		return rowList.FindAll(x => x.mpl_hostname == find);
	}
	public Row Find_mpl_letter(string find)
	{
		return rowList.Find(x => x.mpl_letter == find);
	}
	public List<Row> FindAll_mpl_letter(string find)
	{
		return rowList.FindAll(x => x.mpl_letter == find);
	}
	public Row Find_mpl_def(string find)
	{
		return rowList.Find(x => x.mpl_def == find);
	}
	public List<Row> FindAll_mpl_def(string find)
	{
		return rowList.FindAll(x => x.mpl_def == find);
	}
	public Row Find_mpl_reflink(string find)
	{
		return rowList.Find(x => x.mpl_reflink == find);
	}
	public List<Row> FindAll_mpl_reflink(string find)
	{
		return rowList.FindAll(x => x.mpl_reflink == find);
	}
	public Row Find_mpl_discmethod(string find)
	{
		return rowList.Find(x => x.mpl_discmethod == find);
	}
	public List<Row> FindAll_mpl_discmethod(string find)
	{
		return rowList.FindAll(x => x.mpl_discmethod == find);
	}
	public Row Find_mpl_pnum(string find)
	{
		return rowList.Find(x => x.mpl_pnum == find);
	}
	public List<Row> FindAll_mpl_pnum(string find)
	{
		return rowList.FindAll(x => x.mpl_pnum == find);
	}
	public Row Find_mpl_orbper(string find)
	{
		return rowList.Find(x => x.mpl_orbper == find);
	}
	public List<Row> FindAll_mpl_orbper(string find)
	{
		return rowList.FindAll(x => x.mpl_orbper == find);
	}
	public Row Find_mpl_orbpererr1(string find)
	{
		return rowList.Find(x => x.mpl_orbpererr1 == find);
	}
	public List<Row> FindAll_mpl_orbpererr1(string find)
	{
		return rowList.FindAll(x => x.mpl_orbpererr1 == find);
	}
	public Row Find_mpl_orbpererr2(string find)
	{
		return rowList.Find(x => x.mpl_orbpererr2 == find);
	}
	public List<Row> FindAll_mpl_orbpererr2(string find)
	{
		return rowList.FindAll(x => x.mpl_orbpererr2 == find);
	}
	public Row Find_mpl_orbperlim(string find)
	{
		return rowList.Find(x => x.mpl_orbperlim == find);
	}
	public List<Row> FindAll_mpl_orbperlim(string find)
	{
		return rowList.FindAll(x => x.mpl_orbperlim == find);
	}
	public Row Find_mpl_orbsmax(string find)
	{
		return rowList.Find(x => x.mpl_orbsmax == find);
	}
	public List<Row> FindAll_mpl_orbsmax(string find)
	{
		return rowList.FindAll(x => x.mpl_orbsmax == find);
	}
	public Row Find_mpl_orbsmaxerr1(string find)
	{
		return rowList.Find(x => x.mpl_orbsmaxerr1 == find);
	}
	public List<Row> FindAll_mpl_orbsmaxerr1(string find)
	{
		return rowList.FindAll(x => x.mpl_orbsmaxerr1 == find);
	}
	public Row Find_mpl_orbsmaxerr2(string find)
	{
		return rowList.Find(x => x.mpl_orbsmaxerr2 == find);
	}
	public List<Row> FindAll_mpl_orbsmaxerr2(string find)
	{
		return rowList.FindAll(x => x.mpl_orbsmaxerr2 == find);
	}
	public Row Find_mpl_orbsmaxlim(string find)
	{
		return rowList.Find(x => x.mpl_orbsmaxlim == find);
	}
	public List<Row> FindAll_mpl_orbsmaxlim(string find)
	{
		return rowList.FindAll(x => x.mpl_orbsmaxlim == find);
	}
	public Row Find_mpl_orbeccen(string find)
	{
		return rowList.Find(x => x.mpl_orbeccen == find);
	}
	public List<Row> FindAll_mpl_orbeccen(string find)
	{
		return rowList.FindAll(x => x.mpl_orbeccen == find);
	}
	public Row Find_mpl_orbeccenerr1(string find)
	{
		return rowList.Find(x => x.mpl_orbeccenerr1 == find);
	}
	public List<Row> FindAll_mpl_orbeccenerr1(string find)
	{
		return rowList.FindAll(x => x.mpl_orbeccenerr1 == find);
	}
	public Row Find_mpl_orbeccenerr2(string find)
	{
		return rowList.Find(x => x.mpl_orbeccenerr2 == find);
	}
	public List<Row> FindAll_mpl_orbeccenerr2(string find)
	{
		return rowList.FindAll(x => x.mpl_orbeccenerr2 == find);
	}
	public Row Find_mpl_orbeccenlim(string find)
	{
		return rowList.Find(x => x.mpl_orbeccenlim == find);
	}
	public List<Row> FindAll_mpl_orbeccenlim(string find)
	{
		return rowList.FindAll(x => x.mpl_orbeccenlim == find);
	}
	public Row Find_mpl_orbincl(string find)
	{
		return rowList.Find(x => x.mpl_orbincl == find);
	}
	public List<Row> FindAll_mpl_orbincl(string find)
	{
		return rowList.FindAll(x => x.mpl_orbincl == find);
	}
	public Row Find_mpl_orbinclerr1(string find)
	{
		return rowList.Find(x => x.mpl_orbinclerr1 == find);
	}
	public List<Row> FindAll_mpl_orbinclerr1(string find)
	{
		return rowList.FindAll(x => x.mpl_orbinclerr1 == find);
	}
	public Row Find_mpl_orbinclerr2(string find)
	{
		return rowList.Find(x => x.mpl_orbinclerr2 == find);
	}
	public List<Row> FindAll_mpl_orbinclerr2(string find)
	{
		return rowList.FindAll(x => x.mpl_orbinclerr2 == find);
	}
	public Row Find_mpl_orbincllim(string find)
	{
		return rowList.Find(x => x.mpl_orbincllim == find);
	}
	public List<Row> FindAll_mpl_orbincllim(string find)
	{
		return rowList.FindAll(x => x.mpl_orbincllim == find);
	}
	public Row Find_mpl_bmassj(string find)
	{
		return rowList.Find(x => x.mpl_bmassj == find);
	}
	public List<Row> FindAll_mpl_bmassj(string find)
	{
		return rowList.FindAll(x => x.mpl_bmassj == find);
	}
	public Row Find_mpl_bmassjerr1(string find)
	{
		return rowList.Find(x => x.mpl_bmassjerr1 == find);
	}
	public List<Row> FindAll_mpl_bmassjerr1(string find)
	{
		return rowList.FindAll(x => x.mpl_bmassjerr1 == find);
	}
	public Row Find_mpl_bmassjerr2(string find)
	{
		return rowList.Find(x => x.mpl_bmassjerr2 == find);
	}
	public List<Row> FindAll_mpl_bmassjerr2(string find)
	{
		return rowList.FindAll(x => x.mpl_bmassjerr2 == find);
	}
	public Row Find_mpl_bmassjlim(string find)
	{
		return rowList.Find(x => x.mpl_bmassjlim == find);
	}
	public List<Row> FindAll_mpl_bmassjlim(string find)
	{
		return rowList.FindAll(x => x.mpl_bmassjlim == find);
	}
	public Row Find_mpl_bmassprov(string find)
	{
		return rowList.Find(x => x.mpl_bmassprov == find);
	}
	public List<Row> FindAll_mpl_bmassprov(string find)
	{
		return rowList.FindAll(x => x.mpl_bmassprov == find);
	}
	public Row Find_mpl_radj(string find)
	{
		return rowList.Find(x => x.mpl_radj == find);
	}
	public List<Row> FindAll_mpl_radj(string find)
	{
		return rowList.FindAll(x => x.mpl_radj == find);
	}
	public Row Find_mpl_radjerr1(string find)
	{
		return rowList.Find(x => x.mpl_radjerr1 == find);
	}
	public List<Row> FindAll_mpl_radjerr1(string find)
	{
		return rowList.FindAll(x => x.mpl_radjerr1 == find);
	}
	public Row Find_mpl_radjerr2(string find)
	{
		return rowList.Find(x => x.mpl_radjerr2 == find);
	}
	public List<Row> FindAll_mpl_radjerr2(string find)
	{
		return rowList.FindAll(x => x.mpl_radjerr2 == find);
	}
	public Row Find_mpl_radjlim(string find)
	{
		return rowList.Find(x => x.mpl_radjlim == find);
	}
	public List<Row> FindAll_mpl_radjlim(string find)
	{
		return rowList.FindAll(x => x.mpl_radjlim == find);
	}
	public Row Find_mpl_dens(string find)
	{
		return rowList.Find(x => x.mpl_dens == find);
	}
	public List<Row> FindAll_mpl_dens(string find)
	{
		return rowList.FindAll(x => x.mpl_dens == find);
	}
	public Row Find_mpl_denserr1(string find)
	{
		return rowList.Find(x => x.mpl_denserr1 == find);
	}
	public List<Row> FindAll_mpl_denserr1(string find)
	{
		return rowList.FindAll(x => x.mpl_denserr1 == find);
	}
	public Row Find_mpl_denserr2(string find)
	{
		return rowList.Find(x => x.mpl_denserr2 == find);
	}
	public List<Row> FindAll_mpl_denserr2(string find)
	{
		return rowList.FindAll(x => x.mpl_denserr2 == find);
	}
	public Row Find_mpl_denslim(string find)
	{
		return rowList.Find(x => x.mpl_denslim == find);
	}
	public List<Row> FindAll_mpl_denslim(string find)
	{
		return rowList.FindAll(x => x.mpl_denslim == find);
	}
	public Row Find_ra(string find)
	{
		return rowList.Find(x => x.ra == find);
	}
	public List<Row> FindAll_ra(string find)
	{
		return rowList.FindAll(x => x.ra == find);
	}
	public Row Find_raerr(string find)
	{
		return rowList.Find(x => x.raerr == find);
	}
	public List<Row> FindAll_raerr(string find)
	{
		return rowList.FindAll(x => x.raerr == find);
	}
	public Row Find_dec(string find)
	{
		return rowList.Find(x => x.dec == find);
	}
	public List<Row> FindAll_dec(string find)
	{
		return rowList.FindAll(x => x.dec == find);
	}
	public Row Find_decerr(string find)
	{
		return rowList.Find(x => x.decerr == find);
	}
	public List<Row> FindAll_decerr(string find)
	{
		return rowList.FindAll(x => x.decerr == find);
	}
	public Row Find_mst_teff(string find)
	{
		return rowList.Find(x => x.mst_teff == find);
	}
	public List<Row> FindAll_mst_teff(string find)
	{
		return rowList.FindAll(x => x.mst_teff == find);
	}
	public Row Find_mst_tefferr1(string find)
	{
		return rowList.Find(x => x.mst_tefferr1 == find);
	}
	public List<Row> FindAll_mst_tefferr1(string find)
	{
		return rowList.FindAll(x => x.mst_tefferr1 == find);
	}
	public Row Find_mst_tefferr2(string find)
	{
		return rowList.Find(x => x.mst_tefferr2 == find);
	}
	public List<Row> FindAll_mst_tefferr2(string find)
	{
		return rowList.FindAll(x => x.mst_tefferr2 == find);
	}
	public Row Find_mst_tefflim(string find)
	{
		return rowList.Find(x => x.mst_tefflim == find);
	}
	public List<Row> FindAll_mst_tefflim(string find)
	{
		return rowList.FindAll(x => x.mst_tefflim == find);
	}
	public Row Find_mst_teffblend(string find)
	{
		return rowList.Find(x => x.mst_teffblend == find);
	}
	public List<Row> FindAll_mst_teffblend(string find)
	{
		return rowList.FindAll(x => x.mst_teffblend == find);
	}
	public Row Find_mst_mass(string find)
	{
		return rowList.Find(x => x.mst_mass == find);
	}
	public List<Row> FindAll_mst_mass(string find)
	{
		return rowList.FindAll(x => x.mst_mass == find);
	}
	public Row Find_mst_masserr1(string find)
	{
		return rowList.Find(x => x.mst_masserr1 == find);
	}
	public List<Row> FindAll_mst_masserr1(string find)
	{
		return rowList.FindAll(x => x.mst_masserr1 == find);
	}
	public Row Find_mst_masserr2(string find)
	{
		return rowList.Find(x => x.mst_masserr2 == find);
	}
	public List<Row> FindAll_mst_masserr2(string find)
	{
		return rowList.FindAll(x => x.mst_masserr2 == find);
	}
	public Row Find_mst_masslim(string find)
	{
		return rowList.Find(x => x.mst_masslim == find);
	}
	public List<Row> FindAll_mst_masslim(string find)
	{
		return rowList.FindAll(x => x.mst_masslim == find);
	}
	public Row Find_mst_massblend(string find)
	{
		return rowList.Find(x => x.mst_massblend == find);
	}
	public List<Row> FindAll_mst_massblend(string find)
	{
		return rowList.FindAll(x => x.mst_massblend == find);
	}
	public Row Find_mst_rad(string find)
	{
		return rowList.Find(x => x.mst_rad == find);
	}
	public List<Row> FindAll_mst_rad(string find)
	{
		return rowList.FindAll(x => x.mst_rad == find);
	}
	public Row Find_mst_raderr1(string find)
	{
		return rowList.Find(x => x.mst_raderr1 == find);
	}
	public List<Row> FindAll_mst_raderr1(string find)
	{
		return rowList.FindAll(x => x.mst_raderr1 == find);
	}
	public Row Find_mst_raderr2(string find)
	{
		return rowList.Find(x => x.mst_raderr2 == find);
	}
	public List<Row> FindAll_mst_raderr2(string find)
	{
		return rowList.FindAll(x => x.mst_raderr2 == find);
	}
	public Row Find_mst_radlim(string find)
	{
		return rowList.Find(x => x.mst_radlim == find);
	}
	public List<Row> FindAll_mst_radlim(string find)
	{
		return rowList.FindAll(x => x.mst_radlim == find);
	}
	public Row Find_mst_radblend(string find)
	{
		return rowList.Find(x => x.mst_radblend == find);
	}
	public List<Row> FindAll_mst_radblend(string find)
	{
		return rowList.FindAll(x => x.mst_radblend == find);
	}
	public Row Find_rowupdate(string find)
	{
		return rowList.Find(x => x.rowupdate == find);
	}
	public List<Row> FindAll_rowupdate(string find)
	{
		return rowList.FindAll(x => x.rowupdate == find);
	}

}
*/