// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class GlobularClusterCSV : MonoBehaviour
{
	public TextAsset file;

	private string id;
	private string stellar_type;
	private float mass_su;
	private float luminosity_su;
	private float temp_k;
	private float pos_x;
	private float pos_y;
	private float pos_z;

	void Start ()
	{
		Load (file);
	}

	public class Row
	{
		public string id;
		public string stellar_type;
		public string mass_su;
		public string luminosity_su;
		public string temp_k;
		public string pos_x;
		public string pos_y;
		public string pos_z;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		var scale = 1000;

		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			
			Row row = new Row();
			row.id = grid[i][0];
			row.stellar_type = grid[i][1];
			row.mass_su = grid[i][2];
			row.luminosity_su = grid[i][3];
			row.temp_k = grid[i][4];
			row.pos_x = grid[i][5];
			row.pos_y = grid[i][6];
			row.pos_z = grid[i][7];

			id = row.id;
			stellar_type = row.stellar_type;
			mass_su =  float.Parse (row.mass_su);
			luminosity_su = float.Parse (row.luminosity_su);
			temp_k = float.Parse (row.temp_k);
			pos_x = scale * (float.Parse (row.pos_x));
			pos_y = scale * (float.Parse (row.pos_y));
			pos_z = scale * (float.Parse (row.pos_z));

			new star (id, stellar_type, mass_su, luminosity_su, temp_k, pos_x, pos_y, pos_z);

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public class star {

		//private float planetZ;
		//private float orbitDiameter;

		public star( 
			string id,
			string stellar_type,
			float mass_su,
			float luminosity_su,
			float temp_k,
			float pos_x,
			float pos_y,
			float pos_z
		)
		{

			//create new star primitive
			GameObject star = GameObject.CreatePrimitive (PrimitiveType.Sphere);
			star.name = id;
			star.tag = "star";
			star.transform.position = new Vector3 (pos_x, pos_y, pos_z);
			star.transform.localScale = new Vector3 (1,1,1);

			// Add properties to StellarSystemProps script to be access when creating new scene
//			star.AddComponent<StellarSystemProps>();
//			var starProps = star.GetComponent<StellarSystemProps>();
//			starProps.starName = starName;
//			starProps.starX = starX;
//			starProps.starY = starY; 
//			starProps.starZ = starZ; 
//			starProps.starColor = starColor; 
//			starProps.starRadius = starRadius; 
//			starProps.planetName = planetName;
//			starProps.planetOrbMax = planetOrbMax;
//			starProps.planetRadius = planetRadius;

			// Add star rigidbody component
			Rigidbody starRigidBody = star.AddComponent<Rigidbody> ();
			starRigidBody.mass = 0;
			starRigidBody.useGravity = false;
			starRigidBody.isKinematic = true;


			Material emmisiveStarMaterial = Resources.Load ("Emmisive", typeof(Material)) as Material;
			star.GetComponent<Renderer>().material = emmisiveStarMaterial;
			//Define star color attributes
			//			Material blueStarMaterial = Resources.Load ("blueStarMaterial", typeof(Material)) as Material;
			//			Material cyanStarMaterial = Resources.Load ("cyanStarMaterial", typeof(Material)) as Material;
			//			Material yellowStarMaterial = Resources.Load ("yellowStarMaterial", typeof(Material)) as Material;
			//			Material greenStarMaterial = Resources.Load ("greenStarMaterial", typeof(Material)) as Material;
			//			Material orangeStarMaterial = Resources.Load ("orangeStarMaterial", typeof(Material)) as Material;
			//			Material redStarMaterial = Resources.Load ("redStarMaterial", typeof(Material)) as Material;
//			Material orbitalSphereMaterial = Resources.Load ("orbitalSphereMaterial", typeof(Material)) as Material;
//
//			Material blueStarMaterial = Resources.Load ("LocalStarBody-Blue-001", typeof(Material)) as Material;
//			Material yellowStarMaterial = Resources.Load ("LocalStarBody-Yellow-001", typeof(Material)) as Material;
//			Material orangeStarMaterial = Resources.Load ("LocalStarBody-Orange-001", typeof(Material)) as Material;
//			Material redStarMaterial = Resources.Load ("LocalStarBody-Red-001", typeof(Material)) as Material;
//
//			if(starColor <= 3500)
//			{
//				star.GetComponent<Renderer>().material = redStarMaterial;
//			}
//			else if(starColor >= 3501 && starColor <= 5000)
//			{
//				star.GetComponent<Renderer>().material = orangeStarMaterial;
//			}
//			else if(starColor >= 5001 && starColor <= 6000)
//			{
//				star.GetComponent<Renderer>().material = yellowStarMaterial;
//			}
//			else if(starColor >= 6001 )
//			{
//				star.GetComponent<Renderer>().material = blueStarMaterial;
//			}
			//			else if(starColor >= 4001 && starColor <= 5000)
			//			{
			//				star.GetComponent<Renderer>().material = greenStarMaterial;
			//			}
			//			else if(starColor >= 5001 && starColor <= 8000)
			//			{
			//				star.GetComponent<Renderer>().material = cyanStarMaterial;
			//			}
			//			else if (starColor >= 8001)
			//			{
			//				star.GetComponent<Renderer>().material = blueStarMaterial;
			//			}

			//Create new planet primitive
//			GameObject planet = GameObject.CreatePrimitive (PrimitiveType.Sphere);
//			planet.transform.parent = star.transform;
//			planet.AddComponent<Orbiter>();
//			planet.GetComponent<Orbiter>().orbitSpeed = 5;
//			planet.name = planetName;
//			planet.tag = "planet";
//			var planetZ = starZ + planetOrbMax;
//			planet.transform.position = new Vector3 (starX, starY, planetZ);
//			planet.transform.localScale = new Vector3 (planetRadius, planetRadius, planetRadius); 

			//// Add star rigidbody component
//			Rigidbody planetRigidBody = planet.AddComponent<Rigidbody> ();
//			planetRigidBody.mass = 0;
//			planetRigidBody.useGravity = false;
//			planetRigidBody.isKinematic = true;
//
//			TrailRenderer planetTrail;
//			GameObject planetTrailObj = new GameObject();
//			planetTrailObj.name = planetName + "_trail";
//			planetTrailObj.transform.parent = planet.transform;
//			planetTrailObj.transform.localPosition = Vector3.zero;
//			planetTrail = planetTrailObj.AddComponent<TrailRenderer>();
//			planetTrail.time = Mathf.Infinity;
//			planetTrail.startWidth = 0.1F;
//			planetTrail.endWidth = 0.1F;
//			planetTrailObj.GetComponent<TrailRenderer>().material = orbitalSphereMaterial;

			//Create new text element and attach object label script
			//			GameObject canvas = GameObject.FindGameObjectWithTag("CanvasLabels");
			//			GameObject textGO = new GameObject (starName + "_labelCont");
			//			textGO.transform.SetParent (canvas.transform);
			//			var text = textGO.AddComponent<GUIText> ();
			//			text.text = starName;
			//			var objLabel = textGO.AddComponent<ObjectLabel> ();
			//			objLabel.target = star.transform;
			//			objLabel.clampToScreen = true;
		}
	}



	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_stellar_type(string find)
	{
		return rowList.Find(x => x.stellar_type == find);
	}
	public List<Row> FindAll_stellar_type(string find)
	{
		return rowList.FindAll(x => x.stellar_type == find);
	}
	public Row Find_mass_su(string find)
	{
		return rowList.Find(x => x.mass_su == find);
	}
	public List<Row> FindAll_mass_su(string find)
	{
		return rowList.FindAll(x => x.mass_su == find);
	}
	public Row Find_luminosity_su(string find)
	{
		return rowList.Find(x => x.luminosity_su == find);
	}
	public List<Row> FindAll_luminosity_su(string find)
	{
		return rowList.FindAll(x => x.luminosity_su == find);
	}
	public Row Find_temp_k(string find)
	{
		return rowList.Find(x => x.temp_k == find);
	}
	public List<Row> FindAll_temp_k(string find)
	{
		return rowList.FindAll(x => x.temp_k == find);
	}
	public Row Find_pos_x(string find)
	{
		return rowList.Find(x => x.pos_x == find);
	}
	public List<Row> FindAll_pos_x(string find)
	{
		return rowList.FindAll(x => x.pos_x == find);
	}
	public Row Find_pos_y(string find)
	{
		return rowList.Find(x => x.pos_y == find);
	}
	public List<Row> FindAll_pos_y(string find)
	{
		return rowList.FindAll(x => x.pos_y == find);
	}
	public Row Find_pos_z(string find)
	{
		return rowList.Find(x => x.pos_z == find);
	}
	public List<Row> FindAll_pos_z(string find)
	{
		return rowList.FindAll(x => x.pos_z == find);
	}

}